JOIN_CB = "join"
DONT_VOTE_FOR_ANYONE_CB = "dont_vote_for_anyone"
FINISH_REGISTRATION_CB = "finish_registration"
DRAW_CB = "draw"
POLICEMAN_KILLS_CB = "policeman_kills"
POLICEMAN_CHECKS_CB = "policeman_checks"
PLAYER_BACKS_CB = "player_backs"
WEREWOLF_TO_MAFIA_CB = "to_mafia"
WEREWOLF_TO_DOCTOR_CB = "to_doctor"
WEREWOLF_TO_POLICEMAN_CB = "to_policeman"
POISONER_KILLS_CB = "poisoner_kills"
POISONER_POISONS_CB = "poisoner_poisons"

MENU_CB = "menu"
EDIT_SETTINGS_CB = "edit_settings"
VIEW_ORDER_OF_ROLES_CB = "view_order_of_roles"
VIEW_BANNED_ROLES_CB = "ban_roles"
EDIT_ORDER_OF_ROLES_CB = "edit_order_of_roles"
EDIT_BANNED_ROLES_CB = "edit_banned_roles"
CLEAR_ORDER_OF_ROLES_CB = "clear_order_of_roles"
CLEAR_BANNED_ROLES_CB = "clear_banned_roles"
BAN_EVERYTHING_CB = "ban_everything"
SAVE_ORDER_OF_ROLES_CB = "save_order_of_roles"
SAVE_BANNED_ROLES_CB = "save_banned_roles"
CANCEL_CB = "cancel"
LENGTH_OF_NIGHT_CB = "length_of_night"
LENGTH_OF_DAY_CB = "length_of_day"
ACTIONS_ON_SETTINGS_CB = "actions_on_settings"
DELETE_LATEST_ROLE_IN_ORDER_CB = "pop_latest"
VIEW_ROLES_CB = "view_roles"
FOG_OF_WAR_CB = "fog_of_war"
DIFFERENT_SETTINGS_CB = "different_settings"

SHOW_DEAD_ROLES_AFTER_NIGHT_CB = "show_dead_roles_after_night"
SHOW_DEAD_ROLES_AFTER_HANGING_CB = "show_dead_roles_after_hanging"
SHOW_ROLES_DIED_DUE_TO_INACTIVITY_CB = (
    "show_roles_died_due_to_inactivity"
)
SHOW_KILLERS_CB = "show_killers"
SHOW_INFORMATION_IN_SHARED_CHAT_CB = (
    "show_information_in_shared_chat"
)
SHOW_INFORMATION_ABOUT_GUESTS_AT_NIGHT_CB = (
    "show_information_about_guests_at_night"
)
SHOW_USERNAMES_DURING_VOTING_CB = "show_usernames_during_voting"

HELP_CB = "help"
HOW_TO_START_GAME_CB = "how_to_start_game"
WHAT_ARE_BIDS_CB = "what_are_bids"
HOW_TO_PLAY_CB = "how_to_play"
HOW_TO_SET_UP_GAME_CB = "how_to_set_up_game"
HOW_TO_SEE_STATISTICS_CB = "what_are_statistics"
