"""empty message

Revision ID: 8769b82d4ad6
Revises: 6aa88d85c68d
Create Date: 2025-06-20 18:13:56.736018

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8769b82d4ad6"
down_revision: Union[str, None] = "6aa88d85c68d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "can_talk_at_night",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "can_talk_at_night")
    # ### end Alembic commands ###
