"""empty message

Revision ID: 23b6fd1f7070
Revises: 991c53817bfe
Create Date: 2025-04-27 14:09:31.168616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23b6fd1f7070"
down_revision: Union[str, None] = "991c53817bfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "show_dead_roles_after_night",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "show_dead_roles_after_hanging",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "show_roles_died_due_to_inactivity",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "show_killers",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "show_information_in_shared_chat",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "show_information_about_guests_at_night",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "can_kill_teammates",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "can_marshal_kill",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "can_marshal_kill")
    op.drop_column("settings", "can_kill_teammates")
    op.drop_column(
        "settings", "show_information_about_guests_at_night"
    )
    op.drop_column("settings", "show_information_in_shared_chat")
    op.drop_column("settings", "show_killers")
    op.drop_column("settings", "show_roles_died_due_to_inactivity")
    op.drop_column("settings", "show_dead_roles_after_hanging")
    op.drop_column("settings", "show_dead_roles_after_night")
    # ### end Alembic commands ###
