"""empty message

Revision ID: 55e5e6628014
Revises: 41f798e2b9f8
Create Date: 2025-05-06 17:03:29.044293

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55e5e6628014"
down_revision: Union[str, None] = "41f798e2b9f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "speed_up_nights_and_voting",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "speed_up_nights_and_voting")
    # ### end Alembic commands ###
