"""empty message

Revision ID: 7649176d8eb4
Revises: 6d3ab1e04e7a
Create Date: 2025-03-19 16:49:56.140073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7649176d8eb4"
down_revision: Union[str, None] = "6d3ab1e04e7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("tg_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column(
            "registration_date",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("tg_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
