"""empty message

Revision ID: 8129320b852f
Revises: 6325ddcb104f
Create Date: 2025-04-28 19:18:06.555848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8129320b852f"
down_revision: Union[str, None] = "6325ddcb104f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "time_for_voting",
            sa.Integer(),
            server_default="35",
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "time_for_confirmation",
            sa.Integer(),
            server_default="35",
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "show_usernames_after_confirmation",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
    )
    op.drop_column("settings", "show_information_in_shared_chat")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "show_information_in_shared_chat",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("settings", "show_usernames_after_confirmation")
    op.drop_column("settings", "time_for_confirmation")
    op.drop_column("settings", "time_for_voting")
    # ### end Alembic commands ###
