"""empty message

Revision ID: 41f798e2b9f8
Revises: 59fd5ce21f30
Create Date: 2025-05-06 14:46:54.610990

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41f798e2b9f8"
down_revision: Union[str, None] = "59fd5ce21f30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "allow_betting", sa.Boolean(), server_default="1", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "allow_betting")
    # ### end Alembic commands ###
