"""empty message

Revision ID: 01d391646939
Revises: 8769b82d4ad6
Create Date: 2025-06-23 17:26:25.370611

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01d391646939"
down_revision: Union[str, None] = "8769b82d4ad6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column(
            "time_for_night",
            sa.Integer(),
            server_default="45",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "time_for_day",
            sa.Integer(),
            server_default="45",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "time_for_voting",
            sa.Integer(),
            server_default="35",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "time_for_confirmation",
            sa.Integer(),
            server_default="35",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "show_roles_after_death",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "show_peaceful_allies",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "show_killers",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "show_information_about_guests_at_night",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "show_usernames_during_voting",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "show_usernames_after_confirmation",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "can_kill_teammates",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "can_marshal_kill",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "can_talk_at_night",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "mafia_every_3",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "allow_betting",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "speed_up_nights_and_voting",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "protect_content",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
    )
    op.drop_constraint(
        "groups_setting_id_fkey", "groups", type_="foreignkey"
    )
    op.drop_column("groups", "setting_id")
    op.add_column(
        "orders", sa.Column("group_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "orders_user_tg_id_fkey", "orders", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "orders",
        "groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("orders", "user_tg_id")
    op.add_column(
        "prohibited_roles",
        sa.Column("group_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "prohibited_roles_user_tg_id_fkey",
        "prohibited_roles",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "prohibited_roles",
        "groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("prohibited_roles", "user_tg_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prohibited_roles",
        sa.Column(
            "user_tg_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "prohibited_roles", type_="foreignkey")
    op.create_foreign_key(
        "prohibited_roles_user_tg_id_fkey",
        "prohibited_roles",
        "users",
        ["user_tg_id"],
        ["tg_id"],
        ondelete="CASCADE",
    )
    op.drop_column("prohibited_roles", "group_id")
    op.add_column(
        "orders",
        sa.Column(
            "user_tg_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.create_foreign_key(
        "orders_user_tg_id_fkey",
        "orders",
        "users",
        ["user_tg_id"],
        ["tg_id"],
        ondelete="CASCADE",
    )
    op.drop_column("orders", "group_id")
    op.add_column(
        "groups",
        sa.Column(
            "setting_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "groups_setting_id_fkey",
        "groups",
        "settings",
        ["setting_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("groups", "protect_content")
    op.drop_column("groups", "speed_up_nights_and_voting")
    op.drop_column("groups", "allow_betting")
    op.drop_column("groups", "mafia_every_3")
    op.drop_column("groups", "can_talk_at_night")
    op.drop_column("groups", "can_marshal_kill")
    op.drop_column("groups", "can_kill_teammates")
    op.drop_column("groups", "show_usernames_after_confirmation")
    op.drop_column("groups", "show_usernames_during_voting")
    op.drop_column(
        "groups", "show_information_about_guests_at_night"
    )
    op.drop_column("groups", "show_killers")
    op.drop_column("groups", "show_peaceful_allies")
    op.drop_column("groups", "show_roles_after_death")
    op.drop_column("groups", "time_for_confirmation")
    op.drop_column("groups", "time_for_voting")
    op.drop_column("groups", "time_for_day")
    op.drop_column("groups", "time_for_night")
    # ### end Alembic commands ###
