"""empty message

Revision ID: 6ca407f80e2a
Revises: 6d3c0908f7d9
Create Date: 2025-06-15 19:14:00.421104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ca407f80e2a"
down_revision: Union[str, None] = "6d3c0908f7d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column(
            "name", sa.Enum("anonymous_letters", name="assets"), nullable=False
        ),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.CheckConstraint("cost > 0"),
        sa.PrimaryKeyConstraint("name"),
    )
    op.add_column(
        "users",
        sa.Column(
            "anonymous_letters",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "anonymous_letters")
    op.drop_table("assets")
    # ### end Alembic commands ###
