"""empty message

Revision ID: 59fd5ce21f30
Revises: 55fea2b95d40
Create Date: 2025-04-29 18:27:01.554497

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59fd5ce21f30"
down_revision: Union[str, None] = "55fea2b95d40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "show_peaceful_allies",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "show_peaceful_allies")
    # ### end Alembic commands ###
