"""empty message

Revision ID: 6d3c0908f7d9
Revises: 4d930e0b6b98
Create Date: 2025-05-10 22:58:59.689585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d3c0908f7d9"
down_revision: Union[str, None] = "4d930e0b6b98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "idx_uniq_group_user", "subscriptions", ["group_id", "user_tg_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("idx_uniq_group_user", "subscriptions", type_="unique")
    # ### end Alembic commands ###
