"""empty message

Revision ID: 017c79831b86
Revises: 55e5e6628014
Create Date: 2025-05-09 14:23:03.348074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "017c79831b86"
down_revision: Union[str, None] = "55e5e6628014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "protect_content", sa.Boolean(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "protect_content")
    # ### end Alembic commands ###
