"""empty message

Revision ID: d39abc03bd7b
Revises: 7649176d8eb4
Create Date: 2025-03-19 16:59:16.352837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d39abc03bd7b"
down_revision: Union[str, None] = "7649176d8eb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("winner", sa.String(), nullable=True),
        sa.Column("number_of_nights", sa.Integer(), nullable=True),
        sa.Column("end", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["winner"], ["groupings.name"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    # ### end Alembic commands ###
