"""empty message

Revision ID: 55fea2b95d40
Revises: 8129320b852f
Create Date: 2025-04-29 16:58:47.911512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55fea2b95d40"
down_revision: Union[str, None] = "8129320b852f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "show_roles_after_death",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
    )
    op.drop_column("settings", "show_roles_died_due_to_inactivity")
    op.drop_column("settings", "show_dead_roles_after_night")
    op.drop_column("settings", "show_dead_roles_after_hanging")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "show_dead_roles_after_hanging",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "show_dead_roles_after_night",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "show_roles_died_due_to_inactivity",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("settings", "show_roles_after_death")
    # ### end Alembic commands ###
