"""empty message

Revision ID: 92ef13773bb0
Revises: bb9ec161d19d
Create Date: 2025-04-06 12:59:26.638480

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92ef13773bb0"
down_revision: Union[str, None] = "bb9ec161d19d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "groups", ["tg_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "groups", type_="unique")
    # ### end Alembic commands ###
