"""initial revision

Revision ID: 6d3ab1e04e7a
Revises: 
Create Date: 2025-03-19 16:42:25.749554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d3ab1e04e7a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groupings",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("grouping", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grouping"], ["groupings.name"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles")
    op.drop_table("groupings")
    # ### end Alembic commands ###
